#! /usr/bin/env python

def configure(ctx):
    ctx.load("version", tooldir="..")
    ctx.find_version("rsync")

def build(bld):
    bld(source="file.ver",
            versions={
                "ssh": (6, 9),
                "bash": (3, )
    })
