#! /usr/bin/env python

def configure(ctx):
    ctx.load("version", tooldir="..")
    ctx.find_version("rsync")

def build(bld):
    node = bld.path.find_or_declare
    bld(versions={
        "ssh": (6, 9),
        "bash": (3, )
    }).create_task('ver',
            node('in.ver'),
            node('out')
    )
